# 1: Basic Array Operations

In [20]:
import numpy as np


In [5]:
my_array = np.array([1,10,-5,20])

In [7]:
my_array

array([ 1, 10, -5, 20])

In [12]:
print(f"The mean is {my_array.mean() }")   #mean,meadin,sd one ekak ehema ganna puluwn

The mean is 6.5


In [15]:
print(f"The mean is {my_array.std() }")

The mean is 9.447221813845593


In [18]:
print(f"Multiplication by 2:  {my_array*2 }")

Multiplication by 2:  [  2  20 -10  40]


# 2. Multi-Dimensional Array Manipulation

In [24]:
my_arr_3x4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])   #element godak

In [26]:
my_arr_3x4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
my_arr_3x4 * 4  

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36],
       [40, 44, 48]])

In [32]:
print(f"inverted matrix: {my_arr_3x4.T}")

inverted matrix: [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [34]:
print(f"inverted matrix:\n {my_arr_3x4.T}")

inverted matrix:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [36]:
print(f"elements in this matrix:\n {my_arr_3x4.size}")

elements in this matrix:
 12


In [38]:
print(f"shape in this matrix:\n {my_arr_3x4.shape}")

shape in this matrix:
 (4, 3)


# Boolean Indexing and Slicing

In [42]:
random_integers = np.random.randint(1, 101, 20) #randint kiynne intiger numbers one nisa dana eka
random_integers

array([61, 73, 64,  3, 91, 58, 80, 88,  7, 48, 43, 28, 81, 32, 10,  6, 28,
       55, 53, 21])

In [52]:
random_integers % 2   # % meka dala even or odd hoyanna


# 1 kiyanne odd 0 kiyanne even

array([1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1])

In [53]:
even_numbers =random_integers[random_integers % 2 == 0]     #even numbers withrak ganna
even_numbers        

array([64, 58, 80, 88, 48, 28, 32, 10,  6, 28])

In [56]:
sliced_array = even_numbers[2:10]    # 2 weni thana idan 19 weni thana wena kam even numbers one nam
sliced_array 

array([80, 88, 48, 28, 32, 10,  6, 28])

# Vectorized Operations

In [69]:
arr1 = np.random.randint(0,10,4)
arr2 = np.random.randint(0,10,4)

print(f"the two arrays are:\n{arr1}\n{arr2}")
                   

the two arrays are:
[8 7 6 2]
[9 7 5 2]


In [70]:
print(f"the sum of two arrays is {arr1+arr2}")
print(f"the difference of two arrays is {arr1-arr2}")
print(f"the multiplication of two arrays is {arr1*arr2}")

the sum of two arrays is [17 14 11  4]
the difference of two arrays is [-1  0  1  0]
the multiplication of two arrays is [72 49 30  4]


In [75]:
np.dot(arr1,arr2)    # ekathuwa wage

np.int64(155)

In [76]:
(arr1*arr2).sum()

np.int64(155)

# Working with Real Data

In [82]:
data_set = np.genfromtxt("data.csv",delimiter=";")  #delimiter kiynne wen kranna one widiha
data_set            #meke mulinma api excel file ekaka data set ekak randomly create kragattha

array([[67.,  5., 64., ..., 16., 32., 53.],
       [88., 71., 30., ..., 43., 60.,  4.],
       [96., 34., 15., ..., 24., 55., 77.],
       ...,
       [49., 78., 20., ..., 37., 33., 72.],
       [28., 14., 19., ..., 27.,  8., 39.],
       [ 6., 75., 88., ..., 23., 99., 44.]], shape=(63, 35))

In [84]:
data_set.sum()

np.float64(111165.0)

In [94]:
column_index = 0
column_data = data_set[:,column_index]    # 1st column eke values tika ganna
column_data

array([67., 88., 96., 45., 37., 86., 93., 48., 12., 14., 25., 86., 98.,
       67., 90., 23.,  1., 49., 75., 14.,  7.,  8., 49., 43., 18.,  1.,
       68., 71., 66., 39., 80., 91., 73.,  8., 18., 65., 65., 58., 53.,
       11., 62., 37., 37., 89., 40., 79., 61., 19., 12., 16., 51., 80.,
       54., 66., 18., 95., 33., 22., 42., 69., 49., 28.,  6.])